### ISSUE TITLE
Ancient dupe bug

### ISSUE THREAD

**Issue by crston** [TheBusyBiscuit/Slimefun4#643]
## Description
Describe your Issue AS DETAILED AS POSSIBLE.

## Server Log
Upload your FULL SERVER LOG (/logs/latest.log) to http://pastebin.com/ and paste your link in here.
Without this File, we may not be able to help you at all.

## Evidence / Proof
Attach as many Screenshots or Videos if possible.
Anything that helps us understand the Issue better, is gonna get your Issue fixed even faster.

https://youtu.be/HtSqCuDSQ8s

## Environment
We need the EXACT VERSIONS of the Software you are using.
This includes your Minecraft Version, your CS-CoreLib version and your Slimefun Version.
If you cannot figure out what versions you are running, then please run /sf versions and
show us the output of that command.

1.12.2 1.5.16

**Comment by mrcoffee1026** [comment]
I cannot duplicate this by any means and feel another plugin may be at work.  Under normal circumstances the pedestals and altars do not eject items during crafting.  In the very rare occasions in the past where items are replaced by the player before the crafting animation had completed... but even that only resulted in "eating" items on the pedistals and sometimes glitching some worthless rune-like-object that could not be used for anything.  Aside from this video I've never seen anything like this occur.

**Comment by mrcoffee1026** [comment]
Well I tried that... but I can't remove an item from the altar once it has been placed as it vanishes instantly and won't allow me to place another item until the animation has completed.  If you meant to remove it from a pedestal and not the alter... I did see that I could remove these items before the animation has finished, I would consider THAT to be a bug.  However, replacing it with a different item means that item gets "eaten"... there is no "duplication"... it simply uses up a different item.

**Comment by madolebr** [comment]
ive had the same issue. hit the altar to begin the crafting and take all of the items out of the pedistals and it will start duping items

**Comment by mrcoffee1026** [comment]
Are you on at least the current release version?  I believe the merge from March 2nd adjusted timings somewhat as I am unable to retrieve an item once it is placed on the altar itself.  This would be from dev build 25 to the current release (4.1.14) and up to dev-31.  Again, I do see that items can be retrieved from the pedestals once the animation has begun and this should be dealt with, but I think the item duplication and altar trick with the altar may already have been resolved if you're running at least the latest release?

**Comment by huynhqtienvtag** [comment]
It occurs on my server too... Although I use the latest version... Strange...

**Comment by madolebr** [comment]
we use the latest version of sf and cscore to ensure that isnt the issue. even did a complete reinstall of both to make sure that there were no issues. if you want i can try to get a recording of it, but i think everyone already knows the issue that's being discussed and how it looks

**Comment by madolebr** [comment]
and i also made an issue report about none of the fixes in the newest update having worked, as the furnaces still dupe, keepinv still dupes soulbound items, flask of knowledge is still broken and doesnt drop xp, the altar dupes. but every time i start an issue thread it gets closed out

**Comment by xLastt** [comment]
Wooo :o 
We are needing a BIG Update xD!

**Comment by huynhqtienvtag** [comment]
We need it... Yeah

**Comment by Kiriaat** [comment]
Sorry for the confusion Mrcoffee, I meant that you take the items out of the pedestal after you click on the altar to start crafting and insert items you want to dupe. After the crafting animation, the altar will start spitting out duplicates of the items.

**Comment by Kiriaat** [comment]
[Slimefun.zip](https://github.com/TheBusyBiscuit/Slimefun4/files/1921773/Slimefun.zip)


Here's a temporary fix I've made for my server to anyone that wants it. Basically makes altar crafting instant & blocks the slimefun guide dupe from this: https://github.com/TheBusyBiscuit/Slimefun4/issues/639

Again, this is a temporary fix meaning I did a pretty sloppy job, so it's good to switch when Slimefun is updated.

**Comment by xLastt** [comment]
giv the sauce ;-)

**Comment by madolebr** [comment]
i tried the slimefun jar u sent, but it did not stop the animation or anything. still able to dupe

**Comment by TheBusyBiscuit** [comment]
Possibly adressed in #683 
You can try out the latest builds and see if the Issue persists:
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/
